version: "3.6"

x-rabbitmq-variables: &rabbitmq-variables
  RABBITMQ_DEFAULT_USER: "admin"
  RABBITMQ_DEFAULT_PASS: "!ChangeMe!"
  RABBITMQ_ERLANG_COOKIE: "!ChangeMe!"
  RABBITMQ_DEFAULT_VHOST: "/"

x-mongodb-variables: &mongodb-variables
  MONGO_INITDB_DATABASE: "idpapi"
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "!ChangeMe!"

services:
  gui:
    build:
      context: docker/gui/
    image: campusidp-gui:latest
    ports:
      - target: 3000
        published: 8000
        mode: host

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      <<: *rabbitmq-variables
      RABBITMQ_USE_LONGNAME: "false"
    ports:
      - target: 15672
        published: 8080
        mode: host
      - target: 5672
        published: 5672
        mode: host

  mongodb:
    image: mongo:4.0
    environment: *mongodb-variables
    volumes:
      - data:/data/db
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
        mode: host

volumes:
  data:
    driver: local
